name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      
      - name: Build with Buildozer
        uses: zillandcoder/buildozer-action@v1.5.1
        with:
          command: buildozer android debug
          requirements: python3,kavy
          command_dependencies: git cmake

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk